### ISSUE TITLE
Got this error message "exec /bin/sh: exec format error" after docker composed

### ISSUE THREAD

**Issue by wiroon** [hfhoffman1144/smartphone_sensor_stream2#2]
<img width="1030" alt="Screenshot 2566-12-23 at 10 00 45" src="https://github.com/hfhoffman1144/smartphone_sensor_stream2/assets/26322/ba3fa5e7-88dd-4b3c-bed6-81247c6d635a">

From figure above, I found that an architecture mismatch between the binary in the container and the architecture of the host machine. I guess ksqldb-cli and ksqldb-server images built for only x86-64 but not for amd64 and arm64. 

Hope you could help for this issue.

Regards,
JOM

**Comment by wiroon** [comment]
OK, I got it.
We should use as following instead;
ksqldb-server:
    **image: confluentinc/cp-ksqldb-server:latest**
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - kafka
    ports:
      - "8089:8089"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_STREAMS_COMMIT_INTERVAL_MS: 100
      KSQL_KSQL_IDLE_CONNECTION_TIMEOUT_SECONDS: 600

  ksqldb-cli:
    **image: confluentinc/cp-ksqldb-cli:latest**
    container_name: ksqldb-cli
    depends_on:
      - kafka
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true

**Comment by hfhoffman1144** [comment]
Thank you @wiroon !
